### ISSUE TITLE
Updating url to caseychu.github.io/spring-simulator/

### ISSUE THREAD

**Issue by Cypressxyx** [bitsofpancake/spring-simulator#1]
Was looking around for how others were creating a spring simulation webapp when I noticed that your page was linking to an old github url with the id bitsofpancake.

Changing http://bitsofpancake.github.io/spring-simulator/
to caseychu.github.io/spring-simulator/
should fix the very minor issue.

**Comment by caseychu** [comment]
Fixed. Thanks, much appreciated!
